# NumPy

In [6]:
# why numpy
# numpy fast, list slow

import time
import numpy as np

# creating large data
size = 1000000

# python list
list1 = list(range(size))
list2 = list(range(size))

# Numpy Array
arr1 = np.array(list1)
arr2 = np.array(list2)

# list addition time
start = time.time()

result_list =[]
for i in range(size):
    result_list.append(list1[i] + list2[i])

end = time.time()

print("List Time:", end - start)

# numpy addition time
start = time.time()

result_array = arr1 + arr2

end = time.time()

print("NumPy Time:", end - start)   

List Time: 0.2941873073577881
NumPy Time: 0.0057299137115478516


In [5]:
import numpy as np
print(np.__version__)

2.4.6


# Array vs List

In [8]:
a = [1,2,3,4] # list
b = np.array([1,2,3,4])
print(a)
print(type(a))
print(b)
print(type(b))

[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
b = np.array([1,2,3,4])
print(b)

[1 2 3 4]


# zero

In [11]:
c = np.zeros(3)
print(c)

[0. 0. 0.]


# One

In [12]:
d = np.ones(4)
print(d)

[1. 1. 1. 1.]


# Arrange

In [13]:
e = np.arange(0,10)
print(e)

[0 1 2 3 4 5 6 7 8 9]
